.\" SPDX-FileCopyrightText: 2017  StorPool <support@storpool.com>
.\" SPDX-License-Identifier: Apache-2.0
.\"
.Dd September 18, 2017
.Dt SP-IMAGE-TO-VOLUME 1
.Os
.Sh NAME
.Nm sp-image-to-volume
.Nd save a Glance image to an OpenStack module backed by StorPool
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl c Ar client
.Ar image
.Ar volume
.Nm
.Fl V | Fl h
.Sh DESCRIPTION
The
.Nm
utility saves the data from a Glance image to an OpenStack volume using
the StorPool client to attach the volume to the local machine and detach it
afterwards.
Both the Glance image and the Cinder volume must already exist.
.Pp
The
.Nm
utility accepts the following command-line options:
.Bl -tag -width indent
.It Fl c
Specify the OpenStack client program to use
.Pq default: Cm openstack . 
.It Fl h
Display program usage information and exit.
.It Fl V
Display program version information and exit.
.It Fl v
Verbose operation; display diagnostic output.
.El
.Sh ENVIRONMENT
The operation of the
.Nm
utility is affected by the same environment variables as the OpenStack
client tool used and the StorPool client.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr qemu-img 1
.Sh STANDARDS
No standards documentation was harmed in the process of creating
.Nm .
.Sh BUGS
Please report any bugs in
.Nm
to the author.
.Sh AUTHOR
The
.Nm
utility was written by
.An Peter Pentchev Aq openstack-dev@storpool.com
in 2017.
