.\" Copyright (c) 2017  StorPool
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd August 6, 2017
.Dt SP-OPENSTACK 1
.Os
.Sh NAME
.Nm sp-openstack
.Nd install the StorPool OpenStack integration components
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl L Ar paths
.Cm check
.Op Ar components...
.Nm
.Op Fl v
.Op Fl L Ar paths
.Cm detect
.Op Ar components...
.Nm
.Op Fl v
.Op Fl g Ar grpname
.Op Fl L Ar paths
.Op Fl T Ar module
.Op Fl u Ar username
.Cm install
.Op Ar components...
.Nm
.Cm help
.Nm
.Cm version
.Nm
.Op Fl V | Fl h
.Sh DESCRIPTION
The
.Nm
utility looks for the Python modules comprising several OpenStack
components and modifies them so as to enable the use of a StorPool
cluster as an OpenStack block storage backend.
.Pp
The
.Nm
utility accepts the following subcommands:
.Bl -tag -width version
.It Cm check
Check if the StorPool integration has been installed
.It Cm detect
Determine the versions of the installed OpenStack components
.It Cm help
Display program usage information and exit
.It Cm install
Deploy the StorPool integration
.It Cm version
Display program version information and exit
.El
.Pp
The
.Nm
utility accepts the following command-line options:
.Bl -tag -width indent
.It Fl g
Specify the group for the shared state files
.Pq default: Dq spopenstack .
.It Fl h
Display program usage information and exit.
.It Fl L
Specify the paths
.Pq separated by So : Sc
to search for Python modules.
.It Fl T
Use the
.Xr txn-install 1
utility to record the modified files and pass it the specified
module name.
.It Fl u
Specify the service username to add to the group                                                       
.Pq default: the same as the component name .
.It Fl V
Display program version information and exit.
.It Fl v
Verbose operation; display diagnostic output.
.El
.Sh ENVIRONMENT
The operation of the
.Nm
utility is affected by the same environment variables as the Python
interpreter.
Most notably,
.Ev PYTHONPATH
may be used instead of the
.Fl L
command-line option.
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
See which OpenStack components have their Python modules installed:
.Pp
.Dl sp-openstack detect
.Pp
Check whether the specified OpenStack components have been modified for
StorPool support:
.Pp
.Dl sp-openstack check cinder os-brick
.Pp
Install the OpenStack support for all the components:
.Pp
.Dl sp-openstack install
.Pp
.Sh SEE ALSO
.Xr python 1
.Sh STANDARDS
No standards documentation was harmed in the process of creating
.Nm .
.Sh BUGS
Please report any bugs in
.Nm
to the author.
.Sh AUTHOR
The
.Nm
utility was written by
.An Peter Pentchev Aq openstack-dev@storpool.com
in 2016.
