#!/bin/sh
# SPDX-FileCopyrightText: 2016 - 2023  StorPool <support@storpool.com>
# SPDX-License-Identifier: Apache-2.0

set -e

pythonpath()
{
	local pwd="$(pwd)"
	local pypath="$(pwd)/python:$(pwd)/py-contrib"

	if [ -z "$PYTHONPATH" ]; then
		printf -- '%s\n' "$pypath"
	else
		printf -- '%s:%s\n' "$PYTHONPATH" "$pypath"
	fi
}

env PYTHONPATH="$(pythonpath)" python3 -B -u -m sp_osi "$@"
