.\" SPDX-FileCopyrightText: 2017 - 2022  StorPool <support@storpool.com>
.\" SPDX-License-Identifier: Apache-2.0
.\"
.Dd January 19, 2022
.Dt SP-OPENSTACK 1
.Os
.Sh NAME
.Nm sp-openstack
.Nd install the StorPool OpenStack integration components
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl L Ar paths
.Cm check
.Op Ar components...
.Nm
.Op Fl v
.Op Fl L Ar paths
.Cm detect
.Op Ar components...
.Nm
.Op Fl v
.Op Fl g Ar grpname
.Op Fl L Ar paths
.Op Fl u Ar username
.Cm groups
.Op Ar components...
.Nm
.Op Fl v
.Op Fl g Ar grpname
.Op Fl L Ar paths
.Op Fl u Ar username
.Cm install
.Op Ar components...
.Nm
.Cm help
.Nm
.Cm version
.Nm
.Op Fl V | Fl h
.Sh DESCRIPTION
The
.Nm
utility looks for the Python modules comprising several OpenStack
components and modifies them so as to enable the use of a StorPool
cluster as an OpenStack block storage backend.
.Pp
The
.Nm
utility accepts the following subcommands:
.Bl -tag -width version
.It Cm check
Check if the StorPool integration has been installed
.It Cm detect
Determine the versions of the installed OpenStack components
.It Cm groups
Create the
.Dq spopenstack
group, add the service accounts to it, and set up the spool directory
.It Cm help
Display program usage information and exit
.It Cm install
Deploy the StorPool integration
.It Cm version
Display program version information and exit
.El
.Pp
The
.Nm
utility accepts the following command-line options:
.Bl -tag -width indent
.It Fl g
Specify the group for the shared state files
.Pq default: Dq spopenstack .
.It Fl h
Display program usage information and exit.
.It Fl L
Specify the paths
.Pq separated by So : Sc
to search for Python modules.
.It Fl u
Specify the service username to add to the group                                                       
.Pq default: the same as the component name .
.It Fl V
Display program version information and exit.
.It Fl v
Verbose operation; display diagnostic output.
.El
.Sh ENVIRONMENT
The operation of the
.Nm
utility is affected by the same environment variables as the Python
interpreter.
Most notably,
.Ev PYTHONPATH
may be used instead of the
.Fl L
command-line option.
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
See which OpenStack components have their Python modules installed:
.Pp
.Dl sp-openstack detect
.Pp
Check whether the specified OpenStack components have been modified for
StorPool support:
.Pp
.Dl sp-openstack check cinder os-brick
.Pp
Install the OpenStack support for all the components:
.Pp
.Dl sp-openstack install
.Pp
.Sh SEE ALSO
.Xr python 1
.Sh STANDARDS
No standards documentation was harmed in the process of creating
.Nm .
.Sh BUGS
Please report any bugs in
.Nm
to the author.
.Sh AUTHOR
The
.Nm
utility was written by
.An Peter Pentchev Aq openstack-dev@storpool.com
in 2016.
